services:
  php:
    build: .
    container_name: php_swoole
    working_dir: /www/server/swoole
    volumes:
      - ./src:/www/server/swoole/src
      - ./ssl:/www/server/swoole/ssl
    ports:
      - "9501:9501"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/www/server/mysql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
